# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
orbs:
  ruby: circleci/ruby@2.7.1
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          - BUNDLE_VERSION: 2.1.4
          - RAILS_ENV: 'test'

      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASWORD: 'true'
          - MYSQL_ROOT_HOST: '%'

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circle/postgres:9.4

    working_directory: ~/projects/pfc-master

    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
        name: install dependencies
        command: |
          gem isntall bundler -v 2.1.4
          bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
        paths:
          - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: mv config/database.yml.ci config/database.yml

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
        name: Rubocop
        command: bundle exec rubocop --require rubocop-airbnb

      - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"

          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $TEST_FILES

      - store_test_results:
        path: /tmp/test-results
      -store_artifacts:
        path: /tmp/test-results
        destination: test-reseults
